name: google_huawei_availability
description: A Flutter plugin to detect the availability of the Google Play Services and Huawei HMS Services API on Android devices. It can also be used to check the device is a Huawei device or not.
version: 1.2.0
homepage:
repository: 'https://github.com/devdoxconnect/google_huawei_availability'

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: devdox.connect.google_huawei_availability
        pluginClass: GoogleHuaweiAvailabilityPlugin